export default {
  UI_DESIGN:[],
  IMAGES:[
    {
      thumbnail:'https://image.shutterstock.com/image-photo/colorful-flower-on-dark-tropical-260nw-721703848.jpg',
      file:'https://image.shutterstock.com/image-photo/colorful-flower-on-dark-tropical-260nw-721703848.jpg'
    },
    {
      thumbnail:'https://helpx.adobe.com/content/dam/help/en/stock/how-to/visual-reverse-image-search/jcr_content/main-pars/image/visual-reverse-image-search-v2_intro.jpg',
      file:'https://helpx.adobe.com/content/dam/help/en/stock/how-to/visual-reverse-image-search/jcr_content/main-pars/image/visual-reverse-image-search-v2_intro.jpg'
    },
    {
      thumbnail:'https://www.w3schools.com/w3css/img_lights.jpg',
      file:'https://www.w3schools.com/w3css/img_lights.jpg'
    },
    {
      thumbnail:'https://image.shutterstock.com/image-photo/colorful-flower-on-dark-tropical-260nw-721703848.jpg',
      file:'https://image.shutterstock.com/image-photo/colorful-flower-on-dark-tropical-260nw-721703848.jpg'
    },
    {
      thumbnail:'https://helpx.adobe.com/content/dam/help/en/stock/how-to/visual-reverse-image-search/jcr_content/main-pars/image/visual-reverse-image-search-v2_intro.jpg',
      file:'https://helpx.adobe.com/content/dam/help/en/stock/how-to/visual-reverse-image-search/jcr_content/main-pars/image/visual-reverse-image-search-v2_intro.jpg'
    },
    {
      thumbnail:'https://www.w3schools.com/w3css/img_lights.jpg',
      file:'https://www.w3schools.com/w3css/img_lights.jpg'
    },
    {
      thumbnail:'https://image.shutterstock.com/image-photo/colorful-flower-on-dark-tropical-260nw-721703848.jpg',
      file:'https://image.shutterstock.com/image-photo/colorful-flower-on-dark-tropical-260nw-721703848.jpg'
    },
    {
      thumbnail:'https://helpx.adobe.com/content/dam/help/en/stock/how-to/visual-reverse-image-search/jcr_content/main-pars/image/visual-reverse-image-search-v2_intro.jpg',
      file:'https://helpx.adobe.com/content/dam/help/en/stock/how-to/visual-reverse-image-search/jcr_content/main-pars/image/visual-reverse-image-search-v2_intro.jpg'
    },
    {
      thumbnail:'https://www.w3schools.com/w3css/img_lights.jpg',
      file:'https://www.w3schools.com/w3css/img_lights.jpg'
    },
    {
      thumbnail:'https://image.shutterstock.com/image-photo/colorful-flower-on-dark-tropical-260nw-721703848.jpg',
      file:'https://image.shutterstock.com/image-photo/colorful-flower-on-dark-tropical-260nw-721703848.jpg'
    },
    {
      thumbnail:'https://helpx.adobe.com/content/dam/help/en/stock/how-to/visual-reverse-image-search/jcr_content/main-pars/image/visual-reverse-image-search-v2_intro.jpg',
      file:'https://helpx.adobe.com/content/dam/help/en/stock/how-to/visual-reverse-image-search/jcr_content/main-pars/image/visual-reverse-image-search-v2_intro.jpg'
    },
    {
      thumbnail:'https://www.w3schools.com/w3css/img_lights.jpg',
      file:'https://www.w3schools.com/w3css/img_lights.jpg'
    },
    {
      thumbnail:'https://image.shutterstock.com/image-photo/colorful-flower-on-dark-tropical-260nw-721703848.jpg',
      file:'https://image.shutterstock.com/image-photo/colorful-flower-on-dark-tropical-260nw-721703848.jpg'
    },
    {
      thumbnail:'https://helpx.adobe.com/content/dam/help/en/stock/how-to/visual-reverse-image-search/jcr_content/main-pars/image/visual-reverse-image-search-v2_intro.jpg',
      file:'https://helpx.adobe.com/content/dam/help/en/stock/how-to/visual-reverse-image-search/jcr_content/main-pars/image/visual-reverse-image-search-v2_intro.jpg'
    },
    {
      thumbnail:'https://www.w3schools.com/w3css/img_lights.jpg',
      file:'https://www.w3schools.com/w3css/img_lights.jpg'
    }


  ],
  ICONS:[],
  ILLUSTRATIONS:[],
  BACKGROUNDS:[],
  CHARACTERS:[],
  LAYOUTS:[],
  ANIMATION:[],
  AUDIO:[],
  DOCUMENTS:[],
  VIDEOS:[]
}
